# Generated by Django 4.1.5 on 2023-01-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorauth',
            name='email_otp',
            field=models.BooleanField(default=False, verbose_name='Enable Email OTP'),
        ),
        migrations.AlterField(
            model_name='twofactorauth',
            name='mfa_otp',
            field=models.BooleanField(default=False, verbose_name='Enable MFA OTP'),
        ),
    ]
